#!/bin/bash
root="/*"
destination="home/network/BackupAndRestore"
ex_dirs=" --exclude=/dev/* --exclude=/proc/* --exclude=/sys/* --exclude=/tmp/* --exclude=/run/* --exclude=/mnt/* --exclude=/media/* --exclude=/lost+found"
#Declare function
fun_exit()
{
	echo "BYYYYYYEEEEEEEE!!!!!!!"
	exit
}

fun_backup()
{
	clear
	#Add time to backup file
	echo "========================="
	echo 
	echo "Now backing up your files"
	echo
	TIME=`date +%b-%d-%y`

	#use tar to backup all directories
	#and specify files directories to not be included
	tar cvpfz backup-$TIME.tgz $root $ex_dirs 
	echo
	echo
	echo "Files have been backed up yo bitch"
	
}


#main while for menu
while :
do
	#display menu
	echo "================================"
	echo "Welcome to my backup and restore"
	echo "================================"
	echo "1.Select to backup files"
	echo "2.Select to restore files"
	echo "3.Exit"
	echo "Please enter choice from 1-3:"
	echo
	echo
	read option

	case $option in
		1) fun_backup;;
		2) fun_restore;;
		3) fun_exit;;
	esac
done
