#!/bin/bash
ROOT="/*"
DEST="/backup_dir"
EX_DIRS=" --exclude=/root/backup_dir/* --exclude=/dev/* --exclude=/proc/* --exclude=/sys/* --exclude=/tmp/* --exclude=/run/* --exclude=/mnt/* --exclude=/media/* --exclude=/lost+found"
FILE_BACKUP="backup-$TIME.tgz"

#Declare function

fun_exit()
{
	echo "BYYYYYYEEEEEEEE!!!!!!!"
	exit
}

fun_backup()
{	
	if [ "$USER" != "root" ];
	 then
    		echo "You aint root user use sudo"
    		exit
	fi
	clear
	
	#create backup folder if doesnt already exist
	 cd /
	if [ ! -d "backup_dir" ]
	then
        	mkdir -p backup_dir
	fi


	#Add time to backup file
	echo "========================="
	echo 
	echo "Now backing up your files"
	echo
	TIME=`date +%b-%d-%y-%k%M`

	#use tar to backup all directories
	#and specify files directories to not be included
	tar cvpfz $DEST/backup-$TIME.tgz $ROOT $EX_DIRS 
	echo
	echo
	echo "Files have been backed up"
}

fun_dest()
{
	cd $DEST
	ls -lh
}

fun_restore()
{
	clear
	if [ "$USER" != "root" ]; then
  	  	echo "Not root use sudo "
    		exit
	fi
	
	cd /
	mkdir -p restore_dir

	echo "Please choose file you wish to restore from"
	echo "HINT: pick the most recent file using the date"
	cd $DEST
	ls -lh
	echo
	read restfile	
	 
	
	tar xvpfz $restfile -C /restore_dir/
	echo "========================="
	echo "========================="
	echo "Restore complete!!!"

}

#main while for menu
clear
while :
do
	#display menu
	echo "====================================================="
	echo "Welcome to my backup File used to backup your system"
	echo "====================================================="
	echo "1.Select to backup files to the root"
	echo "2.View backup in location"
	echo "3.Select to restore from the Backup into root"
	echo "4.Exit"
	echo "Please enter choice from 1-4:"
	echo "====================================================="
	echo
	read option

	case $option in
		1) fun_backup;;
		2) fun_dest;;
		3) fun_restore;;
		4) fun_exit;;
	esac
done
